apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: delaparra-cloud
resources:
  - postgres-secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - pvc-postgres.yaml
  - nextcloud-deployment.yaml
  - nextcloud-service.yaml
  - pvc-nextcloud.yaml
