apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: next.delaparra.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud-service
                port:
                  number: 80


                  kubectl create deployment demo --image=httpd --port=80
                  kubectl expose deployment demo
                  kubectl create ingress demo-localhost --class=nginx --rule="delaparra.local/*=demo:80"
                  kubectl port-forward --namespace=ingress-nginx service/ingress-nginx-controller 8080:80
                  curl --resolve delaparra.local:8080:127.0.0.1 http://delaparra.local:8080